---
- name: Install webserver
  sudo: true
  apt: pkg=nginx state=present

- name: Configure webserver
  sudo: true
  template: src="nginx_config.j2" dest="/etc/nginx/nginx.conf"
  notify:
    - Reload webserver

- name: Configure virtual hosts
  sudo: true
  template: src="{{ nginx.template }}" dest="/etc/nginx/sites-enabled/{{ nginx.host }}"
  notify:
    - Reload webserver

